### ISSUE TITLE
 java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ChibbyHD** [GetPerms/GetPerms#11]
[02:43:03] [Server thread/WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/GetPerms/GetPerms/master/db/WorldGuard/permission_nodes.txt
[02:43:03] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[02:43:03] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[02:43:03] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[02:43:03] [Server thread/WARN]: 	at java.net.URL.openStream(Unknown Source)
[02:43:03] [Server thread/WARN]: 	at com.github.GetPerms.GetPerms.Main.downloadFile(Main.java:251)
[02:43:03] [Server thread/WARN]: 	at com.github.GetPerms.GetPerms.DatabaseDownloader.getPluginPermissions(DatabaseDownloader.java:44)
[02:43:03] [Server thread/WARN]: 	at com.github.GetPerms.GetPerms.PermissionTask.run(PermissionTask.java:57)
[02:43:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[02:43:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[02:43:03] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[02:43:03] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[02:43:03] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[02:43:03] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[02:43:03] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Smiley43210** [comment]
Thanks for reporting this issue! It's a simple naming error that caused it.

**Comment by Smiley43210** [comment]
Fixed in the latest commit.
